Package: Move Qt MSBuild and Option related classes to core library
With this change, all QtProject/Qt MsBuild related classes are
moved into the core library. Also moves 'Option' related files
into the core library as discussed. Some code needed to be adapted.

Exception: QtVersionProvider and QtModulesEditor need to stay in
package, otherwise they will not be picked up by the MEF component
framework.

Change-Id: I9aacd62df38ebc4a9676c2021bb50b1f99e7b7d0
Reviewed-by: Miguel Costa <miguel.costa@qt.io>